name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build --no-cache --force-rm -t nickhib1/liatrio_exercise:latest .

      - name: run tests
        uses: liatrio/github-actions/apprentice-action@master

      - name: push to docker-hub
        run: |
          docker push nickhib1/liatrio_exercise:latest
