name: Deploy to Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build --no-cache --force-rm -t nickhib1/liatrio_exercise:latest .
        docker push nickhib1/liatrio_exercise:latest

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }} 

    - name: Deploy to Cloud Run
      run: |
        gcloud config set project liatrioproject
        gcloud run deploy liatrioproject \
          --image nickhib1/liatrio_exercise:latest \
          --platform managed

