name: Apprenticeship Interview Exercise

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        uses: liatrio/github-actions/apprentice-action@master
